### ISSUE TITLE
How can i use my custom keyValue

### ISSUE THREAD

**Issue by tamilairy** [abdullahselek/AES-Encryption#1]
I am trying to use my keyValue. But it's not working. need solution

**Comment by abdullahselek** [comment]
Hi @tamilairy can you tell me which way did you follow and what was the error you get?

**Comment by tamilairy** [comment]
String keyValue = "abdullahselek ";
This is the existing key value. i want to use different key value like keyValue = "HJggHJGJHGhhnbjhg8979HjbHJHJg";

**Comment by abdullahselek** [comment]
@tamilairy take a look at new version `0.1` and updated readme file. I think it will work.

**Comment by tamilairy** [comment]
It's working thanks

**Comment by tamilairy** [comment]
can you tell me your hangouts id ?

**Comment by abdullahselek** [comment]
I don't use much hangouts sorry for that, and I am closing the issue.
